from django.db import models

class ddata(models.Model):
    beneficiary = models.CharField(max_length=255)
    claim = models.CharField(max_length=255)
    claim_start_date = models.DateField(auto_now=False)    
    claim_end_date = models.DateField(auto_now=False)
    provider = models.CharField(max_length=255)
    amount_reimbursed = models.IntegerField()
    attending_physician = models.CharField(max_length=255)
    operating_physician = models.CharField(max_length=255)
    other_physician = models.CharField(max_length=255)
    amount_deductible = models.IntegerField()
    diag_code_1 = models.CharField(max_length=255)
    diag_code_2 = models.CharField(max_length=255)
    diag_code_3 = models.CharField(max_length=255)
    gender = models.IntegerField()
    race = models.IntegerField()
    renal_disease = models.BooleanField()
    state = models.IntegerField()
    county = models.IntegerField()
    inpatient_max_reimbursement = models.IntegerField()
    inpatient_max_deductible = models.IntegerField()
    outpatient_max_reimbursement = models.IntegerField()
    outpatient_max_deductible = models.IntegerField()
    age = models.FloatField()
    total_net_amount = models.IntegerField()
    same_physician = models.IntegerField()
    claim_duration = models.IntegerField()
    hospital_duration = models.IntegerField()
    is_4019 = models.BooleanField()
    is_4011 = models.BooleanField()
    fraud_flag = models.BooleanField()
    is_predicted = models.BooleanField()